# Generated by Django 4.1.7 on 2023-03-29 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
